#!/bin/bash
# Remote Compile after clean
# Execute make clean, cmake, and make via SSH on the Raspberry PI after copying source to it

rsync -av ./ pi@pi3:/home/pi/checkouts/embedded/oled_display/

ssh pi@pi3 "cd checkouts/embedded/oled_display/armBuild; make clean; cmake -DCMAKE_BUILD_TYPE=Debug ../; make -j4"


