#!/bin/bash

# Script copies the source to Raspberry Pi, and then executes the build command via SSH

rsync -av ./ pi@pi3:/home/pi/checkouts/embedded/GpioTester/

ssh pi@pi3 "cd checkouts/embedded/GpioTester/armBuild; make -j4"


